syntax on

" use spaces instead of tabs
set expandtab

" set 1 tab to 4 spaces
set shiftwidth=4
set tabstop=4

" show line number
set number
set numberwidth=2

" add command to save file with priviliges
command W :execute ':silent w !sudo tee % > /dev/null' | :edit!

